# Generated by Django 5.1 on 2024-08-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.CharField(max_length=100)),
                ('background_img', models.ImageField(upload_to='background_image/')),
                ('original_image', models.ImageField(upload_to='original/')),
                ('processed_image', models.ImageField(upload_to='masked/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
