# Generated by Django 5.1 on 2024-08-23 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changeBGApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processedimage',
            old_name='UserID',
            new_name='user',
        ),
    ]
